### ISSUE TITLE
sync possible ?

### ISSUE THREAD

**Issue by sergiokessler** [marktennyson/flask-mailing#21]
is there any way to NOT use async ?

whitout async I get:
```
RuntimeWarning: coroutine 'Mail.send_message' was never awaited mailer.send_message(msg)
```

using async is fine, no errors, the mail goes trough,
but everything else in my app is sync, and I don't want to fall in "what color is your function ?"

**Comment by marktennyson** [comment]
Currently we don't have any implementation to support the synchronous view functions. You can start using flask-mailman.
