### ISSUE TITLE
Remove the pydantinc support. It's not necessary. 

### ISSUE THREAD

**Issue by marktennyson** [marktennyson/flask-mailing#24]
Pydantinc isn't required for the flask app.

**Comment by marktennyson** [comment]
it's not possible, because the schema section using it.

**Comment by sr-verde** [comment]
Why is the schema section using Pydantic at all? I don't see a reason for validation. Validation should be the responsibility of the users of the lib. Currently, Flask-Mailing spends resources on validation when it is not necessary and this behavior keeps me from using it.

If anything, Python’s built-in dataclass implemention should fit the use-case, right? I love Pydantic and uses it in almost all my Flask projects (and more) but if I would use Flask-Mailing I would validate all my user input twice.
