### ISSUE TITLE
Error when running on Python 3.11

### ISSUE THREAD

**Issue by rroline** [marktennyson/flask-mailing#40]
Getting an error about a duplicate class with one of the modules used in this library. 

> Sep 21 07:03:38  flaskweb[3047]:     from flask_mailing import Mail
Sep 21 07:03:38  flaskweb[3047]:   File "/usr/local/lib/python3.11/dist-packages/flask_mailing/__init__.py", line 88, in <module>
Sep 21 07:03:38  flaskweb[3047]:     from . import utils
Sep 21 07:03:38  flaskweb[3047]:   File "/usr/local/lib/python3.11/dist-packages/flask_mailing/utils/__init__.py", line 1, in <module>
Sep 21 07:03:38  flaskweb[3047]:     from .email_check import DefaultChecker, WhoIsXmlApi
Sep 21 07:03:38  flaskweb[3047]:   File "/usr/local/lib/python3.11/dist-packages/flask_mailing/utils/email_check.py", line 5, in <module>
Sep 21 07:03:38  flaskweb[3047]:     import aioredis
Sep 21 07:03:38  flaskweb[3047]:   File "/usr/local/lib/python3.11/dist-packages/aioredis/__init__.py", line 1, in <module>
Sep 21 07:03:38  flaskweb[3047]:     from aioredis.client import Redis, StrictRedis
Sep 21 07:03:38  flaskweb[3047]:   File "/usr/local/lib/python3.11/dist-packages/aioredis/client.py", line 32, in <module>
Sep 21 07:03:38  flaskweb[3047]:     from aioredis.connection import (
Sep 21 07:03:38  flaskweb[3047]:   File "/usr/local/lib/python3.11/dist-packages/aioredis/connection.py", line 33, in <module>
Sep 21 07:03:38  flaskweb[3047]:     from .exceptions import (
Sep 21 07:03:38  flaskweb[3047]:   File "/usr/local/lib/python3.11/dist-packages/aioredis/exceptions.py", line 14, in <module>
Sep 21 07:03:38  flaskweb[3047]:     class TimeoutError(asyncio.TimeoutError, builtins.TimeoutError, RedisError):
Sep 21 07:03:38  flaskweb[3047]: TypeError: duplicate base class TimeoutError

**Comment by rroline** [comment]
I the modules used need to be switched from `aioredis` library to `redis` as it looks like they are no longer supported

https://github.com/aio-libs/aioredis-py/issues/1409

**Comment by Master-of-Bytes** [comment]
@rroline Any idea when you will patch this so it works with Python 3.11? Currently working on a project and would like to use your library.

**Comment by marktennyson** [comment]
@rroline @Master-of-Bytes 

This issue is fixed in the new version. Please check release 0.2.1 for the updated code.

**Comment by rroline** [comment]
> @rroline @Master-of-Bytes
> 
> This issue is fixed in the new version. Please check release 0.2.1 for the updated code.

@marktennyson  - Thank you so much! Appreciate the update!
