### ISSUE TITLE
Support for pydantic > 2

### ISSUE THREAD

**Issue by halali** [marktennyson/flask-mailing#54]
https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings

**Comment by CharlesTWood** [comment]
Was about to open this issue also:

`File "/Users/admin/Desktop/repos/venv/lib/python3.11/site-packages/flask_mailing/__init__.py", line 89, in <module>
    from .config import ConnectionConfig
  File "/Users/admin/Desktop/repos/venv/lib/python3.11/site-packages/flask_mailing/config.py", line 7, in <module>
    from pydantic import BaseSettings as Settings
  File "/Users/admin/Desktop/repos/venv/lib/python3.11/site-packages/pydantic/__init__.py", line 210, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Desktop/repos/venv/lib/python3.11/site-packages/pydantic/_migration.py", line 289, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.3/migration/#basesettings-has-moved-to-pydantic-settings for more details.
`

**Comment by CharlesTWood** [comment]
PR for support: https://github.com/marktennyson/flask-mailing/pull/55

**Comment by marktennyson** [comment]
Hello @halali and @CharlesTWood 
This issue is fixed now. 
Please start using `Flask-Mailing V0.2.3`.
